### ISSUE TITLE
Computation of double-fire weapons' burst damage fails for zero length bursts

### ISSUE THREAD

**Issue by sestrand** [lisongmechlab/lsml#755]
**LSML version:** 2.0.12
**Screen resolution:** 3440x1440
**Java version:** 8u301

**Steps to reproduce issue:**
1. Open LSML
2. Click on garage, 
3. Then on as7-D 

**Actual result:**
java.util.NoSuchElementException
	at java.util.AbstractQueue.remove(Unknown Source)
	at org.lisoft.lsml.model.metrics.helpers.DoubleFireBurstSignal.shots(DoubleFireBurstSignal.java:173)
	at org.lisoft.lsml.model.metrics.helpers.DoubleFireBurstSignal.integrateFromZeroTo(DoubleFireBurstSignal.java:67)
	at org.lisoft.lsml.model.metrics.BurstDamageOverTime.calculate(BurstDamageOverTime.java:92)
	at org.lisoft.lsml.model.metrics.RangeTimeMetric.calculate(RangeTimeMetric.java:58)
	at org.lisoft.lsml.view_fx.properties.MetricBinding.computeValue(MetricBinding.java:76)
	at org.lisoft.lsml.view_fx.properties.RangeMetricBinding.computeValue(RangeMetricBinding.java:84)
	at org.lisoft.lsml.view_fx.util.FxBindingUtils$3.<init>(FxBindingUtils.java:274)
	at org.lisoft.lsml.view_fx.util.FxBindingUtils.formatValue(FxBindingUtils.java:271)
	at org.lisoft.lsml.view_fx.util.FxBindingUtils$1.<init>(FxBindingUtils.java:199)
	at org.lisoft.lsml.view_fx.util.FxBindingUtils.format(FxBindingUtils.java:113)
	at org.lisoft.lsml.view_fx.controllers.loadoutwindow.LoadoutInfoPaneController.formatLabel(LoadoutInfoPaneController.java:297)
	at org.lisoft.lsml.view_fx.controllers.loadoutwindow.LoadoutInfoPaneController.setupOffensivePanels(LoadoutInfoPaneController.java:479)
	at org.lisoft.lsml.view_fx.controllers.loadoutwindow.LoadoutInfoPaneController.<init>(LoadoutInfoPaneController.java:226)
	at org.lisoft.lsml.view_fx.DaggerFXApplicationComponent$MechlabSubComponentImpl.getLoadoutInfoPaneController(DaggerFXApplicationComponent.java:396)
	at org.lisoft.lsml.view_fx.DaggerFXApplicationComponent$MechlabSubComponentImpl.mechlabWindow(DaggerFXApplicationComponent.java:427)
	at org.lisoft.lsml.view_fx.LiSongMechLab.lambda$receive$1(LiSongMechLab.java:159)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)

**Expected result:**
loading the AS7-D build. I've tested the 2 builds I had previously.  I'll step through other mechs and see if any other builds fail. I have at least one build of each chasis.

**Comment by sestrand** [comment]
not one of each and every model... but I have a lot. Anyway, I learned more about this crash... the builds that crash are everything I have previously created that has RAC installed.

**Comment by sestrand** [comment]
and creating a new mech and trying to put in a RAC also crashes. (I'll try to uninstall all including JAVA and reinstall, to see if I did this wrong)

java.util.NoSuchElementException
	at java.util.AbstractQueue.remove(Unknown Source)
	at org.lisoft.lsml.model.metrics.helpers.DoubleFireBurstSignal.shots(DoubleFireBurstSignal.java:173)
	at org.lisoft.lsml.model.metrics.helpers.DoubleFireBurstSignal.integrateFromZeroTo(DoubleFireBurstSignal.java:67)
	at org.lisoft.lsml.model.metrics.BurstDamageOverTime.calculate(BurstDamageOverTime.java:92)
	at org.lisoft.lsml.model.metrics.RangeTimeMetric.calculate(RangeTimeMetric.java:58)
	at org.lisoft.lsml.view_fx.properties.MetricBinding.computeValue(MetricBinding.java:76)
	at org.lisoft.lsml.view_fx.properties.RangeMetricBinding.computeValue(RangeMetricBinding.java:84)
	at org.lisoft.lsml.view_fx.util.FxBindingUtils$3.computeValue(FxBindingUtils.java:279)
	at org.lisoft.lsml.view_fx.util.FxBindingUtils$1.computeValue(FxBindingUtils.java:223)
	at org.lisoft.lsml.view_fx.properties.MetricBinding.receive(MetricBinding.java:70)
	at org.lisoft.lsml.messages.MessageXBar.dispatchMessage(MessageXBar.java:127)
	at org.lisoft.lsml.messages.MessageXBar.post(MessageXBar.java:90)
	at org.lisoft.lsml.command.MessageCommand.post(MessageCommand.java:46)
	at org.lisoft.lsml.command.CmdItemBase.post(CmdItemBase.java:95)
	at org.lisoft.lsml.command.CmdItemBase.add(CmdItemBase.java:66)
	at org.lisoft.lsml.command.CmdAddItem.apply(CmdAddItem.java:85)
	at org.lisoft.lsml.util.CommandStack.pushAndApply(CommandStack.java:238)
	at org.lisoft.lsml.view_fx.LiSongMechLab.safeCommand(LiSongMechLab.java:114)
	at org.lisoft.lsml.view_fx.controllers.loadoutwindow.ComponentPaneController.safeCommand(ComponentPaneController.java:214)
	at org.lisoft.lsml.view_fx.controllers.loadoutwindow.ComponentPaneController.onDragDropped(ComponentPaneController.java:171)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.View.handleDragDrop(View.java:712)
	at com.sun.glass.ui.View.notifyDragDrop(View.java:1041)
	at com.sun.glass.ui.win.WinDnDClipboard.push(Native Method)
	at com.sun.glass.ui.win.WinSystemClipboard.pushToSystem(WinSystemClipboard.java:234)
	at com.sun.glass.ui.SystemClipboard.flush(SystemClipboard.java:51)
	at com.sun.glass.ui.ClipboardAssistance.flush(ClipboardAssistance.java:59)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:941)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)

**Comment by sestrand** [comment]
reinstalling (starting with java) did not change the results. crashes on all RAC builds.
