### ISSUE TITLE
Parse error loading after 9/21/21 mwo patch

### ISSUE THREAD

**Issue by sestrand** [lisongmechlab/lsml#758]
**LSML version:** 2.0.13
**Screen resolution:** 3440x1440
**Java version:** 8u301

**Steps to reproduce issue:**
1. Open LSML
2. parse error occurs

**Actual result:**
java.io.IOException: Unable to load chassi configuration! Chassis: arcticwolf
	at org.lisoft.lsml.model.database.gamedata.MwoDataReader.parseOmniPods(MwoDataReader.java:447)
	at org.lisoft.lsml.model.database.gamedata.MwoDataReader.parseGameFiles(MwoDataReader.java:174)
	at org.lisoft.lsml.view_fx.FXDatabaseProvider.updateDatabase(FXDatabaseProvider.java:282)
	at org.lisoft.lsml.view_fx.FXDatabaseProvider.loadDatabase(FXDatabaseProvider.java:257)
	at org.lisoft.lsml.view_fx.FXDatabaseProvider.getDatabase(FXDatabaseProvider.java:102)
	at org.lisoft.lsml.view_fx.LiSongMechLab.backgroundLoad(LiSongMechLab.java:257)
	at org.lisoft.lsml.view_fx.LiSongMechLab.access$000(LiSongMechLab.java:70)
	at org.lisoft.lsml.view_fx.LiSongMechLab$1.call(LiSongMechLab.java:209)
	at org.lisoft.lsml.view_fx.LiSongMechLab$1.call(LiSongMechLab.java:205)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Didn't understand quirk: ammocapacity_cstreak_srm_additive
	at org.lisoft.lsml.model.database.gamedata.QuirkModifiers.createModifierDescription(QuirkModifiers.java:171)
	at org.lisoft.lsml.model.database.gamedata.QuirkModifiers.lambda$createModifier$0(QuirkModifiers.java:58)
	at java.util.HashMap.computeIfAbsent(Unknown Source)
	at org.lisoft.lsml.model.database.gamedata.QuirkModifiers.createModifier(QuirkModifiers.java:58)
	at org.lisoft.lsml.model.database.gamedata.XMLOmniPods.asOmniPods(XMLOmniPods.java:119)
	at org.lisoft.lsml.model.database.gamedata.MwoDataReader.parseOmniPods(MwoDataReader.java:443)
	... 11 more

**Expected result:**
sorry, but there has been an update that brought along a parse error.

**Comment by LiSongMWO** [comment]
That's unfortunate... I'm a bit busy at the moment but I'll take a look as soon as things settle down a bit over here.

**Comment by GidonsClaw** [comment]
Yup, confirmed, same for me...

**Comment by GidonsClaw** [comment]
Can confirm issue still persists with latest November Patch also.

**Comment by LiSongMWO** [comment]
Sorry, life has been crazy the past month still haven't found the time to sit down and look at this. Sorry for the delay.

**Comment by sestrand** [comment]
I am not exactly certain when the November patch occurred, but the parse
 error still was present in lsml yesterday

**Comment by GidonsClaw** [comment]
No worries @LiSongMWO, when ever you can. I love prototyping builds using LSML... I've done some of my best builds there and then just applied to a mech in my bay and whalla.... it's a good build.

Appreciate it.

**Comment by sestrand** [comment]
I agree with Gideon.  while MechDB is improved in their last update, it
still does not match LSML for understanding heat or even ease of building.
