### ISSUE TITLE
XLM parsing issue post May Patch

### ISSUE THREAD

**Issue by GidonsClaw** [lisongmechlab/lsml#773]
**LSML version:** 2.0.14
**Screen resolution:** 2560x1440
**Java version:** 8u333

**Steps to reproduce issue:**
1. Open LSML
2. Error show on load

**Actual result:**
Error message with detail:

`java.io.IOException: Failed to find sought for file (Game\Localized\Languages\TheRealLoc.xml) in the game files!
	at org.lisoft.lsml.model.database.gamedata.GameVFS.openGameFile(GameVFS.java:360)
	at org.lisoft.lsml.model.database.gamedata.Localisation.initialize(Localisation.java:66)
	at org.lisoft.lsml.model.database.gamedata.MwoDataReader.parseGameFiles(MwoDataReader.java:150)
	at org.lisoft.lsml.view_fx.FXDatabaseProvider.updateDatabase(FXDatabaseProvider.java:276)
	at org.lisoft.lsml.view_fx.FXDatabaseProvider.loadDatabase(FXDatabaseProvider.java:251)
	at org.lisoft.lsml.view_fx.FXDatabaseProvider.getDatabase(FXDatabaseProvider.java:102)
	at org.lisoft.lsml.view_fx.LiSongMechLab.backgroundLoad(LiSongMechLab.java:257)
	at org.lisoft.lsml.view_fx.LiSongMechLab.access$000(LiSongMechLab.java:70)
	at org.lisoft.lsml.view_fx.LiSongMechLab$1.call(LiSongMechLab.java:209)
	at org.lisoft.lsml.view_fx.LiSongMechLab$1.call(LiSongMechLab.java:205)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

**Expected result:**
Load as normal

**Comment by sestrand** [comment]
Mine has a different parse error. but same result, wont properly start.

java.io.IOException: Unable to load chassi configuration for [sdr-5dp]!
	at org.lisoft.lsml.model.database.gamedata.MwoDataReader.parseChassis(MwoDataReader.java:281)
	at org.lisoft.lsml.model.database.gamedata.MwoDataReader.parseGameFiles(MwoDataReader.java:177)
	at org.lisoft.lsml.view_fx.FXDatabaseProvider.updateDatabase(FXDatabaseProvider.java:276)
	at org.lisoft.lsml.view_fx.FXDatabaseProvider.loadDatabase(FXDatabaseProvider.java:251)
	at org.lisoft.lsml.view_fx.FXDatabaseProvider.getDatabase(FXDatabaseProvider.java:102)
	at org.lisoft.lsml.view_fx.LiSongMechLab.backgroundLoad(LiSongMechLab.java:257)
	at org.lisoft.lsml.view_fx.LiSongMechLab.access$000(LiSongMechLab.java:70)
	at org.lisoft.lsml.view_fx.LiSongMechLab$1.call(LiSongMechLab.java:209)
	at org.lisoft.lsml.view_fx.LiSongMechLab$1.call(LiSongMechLab.java:205)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No such key found!: @sdr-5dp
	at org.lisoft.lsml.model.database.gamedata.Localisation.key2string(Localisation.java:100)
	at org.lisoft.lsml.model.database.gamedata.MdfMechDefinition.asChassisStandard(MdfMechDefinition.java:133)
	at org.lisoft.lsml.model.database.gamedata.MwoDataReader.parseChassis(MwoDataReader.java:277)
	... 11 more

**Comment by GidonsClaw** [comment]
Latest patch has not fixed the issue unfortunately: https://mwomercs.com/forums/topic/283018-hotfix/

**Comment by sestrand** [comment]
And the June fix is even worse actually.  One thing PGI has done is change the filename and internal path for the English localization file.

**Comment by LiSongMWO** [comment]
This is fixed for 2.0.15 coming out as soon as I iron out some bugs.
